name: Web page
on:
  push:
    branches: ["master"]
  workflow_dispatch:  
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Validate html
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: "dist/"

  deploy:
    needs: [ test ]
    environment: 
      name: github-pages
      url: ${{ steps.deploymentID.outputs.page_url }}
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World
        run: echo "Hello World"
      - name: Clone repository
        uses: actions/checkout@v3
      - name: setup github pages
        uses: actions/configure-pages@v3
      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist/"
      - name: Deployment
        id: deploymentID
        uses: actions/deploy-pages@v2