name: Web page
on:
  push:
    branches: ["master"]
  workflow_dispatch:  
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Validate html
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: dist/
      - name: check environment
        run: echo "${{secrets.author_name}}""
      - name: check version
        run: echo "${{env.version}}"


  deploy:
    needs: [ test ]
    environment: 
      name: github-pages
      url: ${{ steps.deploymentID.outputs.page_url }}
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World
        run: echo "Hello World"
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set Environment
        run: sed -i -e "s/{author_name}/${{secrets.author_name}}/g" dist/index.html
      - name: setup github pages
        uses: actions/configure-pages@v3
      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist/
      - name: Deployment
        id: deploymentID
        uses: actions/deploy-pages@v2